# Generated by Django 2.0.2 on 2018-09-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_subscribe_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='summary',
            field=models.TextField(max_length=200),
        ),
    ]
