# Generated by Django 2.0.2 on 2018-09-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='media/images/Screenshot_9.png', upload_to='images/'),
        ),
    ]
