# Generated by Django 2.0.2 on 2018-09-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180911_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='images/Screenshot_9.png', upload_to='images/'),
        ),
    ]
