# Generated by Django 2.0.2 on 2018-09-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('code', models.CharField(max_length=2)),
                ('res', models.FileField(upload_to='media/')),
            ],
        ),
    ]
