# Generated by Django 2.0.2 on 2018-10-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.TextField(default='courseImage', max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.TextField(default='topicImage', max_length=200),
        ),
    ]
