# Generated by Django 2.0.2 on 2018-09-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('curr', models.IntegerField()),
                ('next', models.IntegerField()),
            ],
        ),
    ]
