# Generated by Django 2.0.2 on 2018-10-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conid', models.IntegerField()),
                ('code', models.CharField(max_length=1)),
                ('data', models.TextField(max_length=300)),
                ('oid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('coursename', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('topicname', models.TextField(max_length=100)),
                ('topicdesc', models.TextField(max_length=200)),
                ('oid', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.course')),
            ],
        ),
        migrations.DeleteModel(
            name='creator',
        ),
        migrations.DeleteModel(
            name='link',
        ),
        migrations.AddField(
            model_name='content',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.topic'),
        ),
    ]
