# Generated by Django 2.0.2 on 2018-10-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0005_auto_20181004_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('conid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('data', models.TextField(max_length=300)),
                ('oid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=200)),
                ('oid', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.course')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.topic'),
        ),
    ]
